name: Merge Repositories
on:
  push:
    branches:
      - main  # Specify the branch you want to trigger the merge on

jobs:
  merge_repositories:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout destination repository
        uses: actions/checkout@v2
        with:
          repository: vskbot007/SteveOCPP  # Specify the destination repository
          path: vskbot007/SteveOCPP  # Specify the directory for the destination repository

      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: steve-community/steve  # Specify the source repository
          path: steve-community/steve  # Specify the directory for the source repository

      - name: Merge changes
        run: |
          cd vskbot007/SteveOCPP
          git remote add steve-community/steve
          git fetch steve-community/steve
          git merge --allow-unrelated-histories steve-community/steve/master  # Specify the source branch to merge

          # Handle conflicts if any
          # git mergetool  # If you want to resolve conflicts interactively

          git commit -am "Merged changes from source repository"

      - name: Push changes
        run: |
          cd vskbot007/SteveOCPP
          git push origin main 
