
name: Merge Repositories
on:
  push:
    branches:
      - main  # Specify the branch you want to trigger the merge on

jobs:
  merge_repositories:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout destination repository
        uses: actions/checkout@v2
        with:
          repository: vsk/SteveOCPP  # Specify the destination repository
          path: vsk/SteveOCPP  # Specify the directory for the destination repository

      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: steve-community/steve  # Specify the source repository
          path: steve-community/steve  # Specify the directory for the source repository

      - name: Merge changes
        run: |
          cd vsk/SteveOCPP
          git remote add steve-community https://github.com/steve-community/steve
          git fetch steve-community
          git merge --allow-unrelated-histories steve-community/steve/master  # Specify the source branch to merge

          # Handle conflicts if any
          # git mergetool  # If you want to resolve conflicts interactively

          git commit -am "Merged changes from source repository"
          
      - name: Fetch latest release
        run: |
          cd vsk/SteveOCPP
          git fetch --tags

      - name: Get latest release tag
        id: latest_release
        run: |
          cd vsk/SteveOCPP
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "::set-output name=tag::$latest_tag"
          
      - name: Checkout latest release
        uses: actions/checkout@v2
        with:
          repository: vsk/SteveOCPP
          ref: ${{ steps.latest_release.outputs.tag }}

      - name: Add branch to destination repository
        run: |
          cd vsk/SteveOCPP
          git checkout -b main  # Create and checkout the new branch
          git push origin main  # Push the new branch to the remote repository

